name: Test & Build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn tsc
      - run: yarn lint
      - run: yarn build
      - name: Check dist/ is up to date
        run: |
          if [ -n "$(git diff --name-only)" ]; then
            echo "dist/ is out of date. Run 'yarn build' and commit the result."
            git diff --stat
            exit 1
          fi
